const GenerateRandomTerminalInputsConstants: string[] = [
    "John@localhost: Hey, what's up?",
    "Emma@localhost: Not much, just chilling.",
    "Michael@localhost: Did you watch the latest episode of that show?",
    "Sophia@localhost: Yeah, it was amazing!",
    "David@localhost: I can't wait for the next season.",
    "Olivia@localhost: Just finished reading a great book.",
    "Daniel@localhost: What's the book about?",
    "Emily@localhost: It's a mystery novel with a twist.",
    "Matthew@localhost: Sounds interesting. I'll check it out.",
    "Ava@localhost: Let me know what you think!",
    "William@localhost: Have you tried the new restaurant in town?",
    "Sofia@localhost: No, not yet. Is it any good?",
    "James@localhost: Yes, the food is delicious!",
    "Charlotte@localhost: I'll have to give it a try.",
    "Benjamin@localhost: Did you hear about the concert next week?",
    "Amelia@localhost: Yeah, I already got my tickets.",
    "Henry@localhost: It's going to be an amazing show.",
    "Mia@localhost: I can't wait to see the band live.",
    "Elijah@localhost: Have you seen the latest movie?",
    "Harper@localhost: No, not yet. Is it worth watching?",
    "Alexander@localhost: Definitely! It's a must-see.",
    "Abigail@localhost: I'll make sure to watch it.",
    "Daniel@localhost: What are your plans for the weekend?",
    "Elizabeth@localhost: I'm going hiking with some friends.",
    "Joseph@localhost: That sounds like a lot of fun.",
    "Evelyn@localhost: Do you have any recommendations for a good book?",
    "William@localhost: I recently read a great sci-fi novel.",
    "Sophia@localhost: What's the title of the book?",
    "Oliver@localhost: It's called 'The Expanse'.",
    "Ava@localhost: I'll add it to my reading list.",
    "Michael@localhost: Did you watch the latest sports game?",
    "Isabella@localhost: Yeah, it was an intense match.",
    "Jacob@localhost: Who won in the end?",
    "Mia@localhost: The home team came out on top.",
    "Emily@localhost: I'm glad they won.",
    "Daniel@localhost: Have you tried the new coffee shop?",
    "Charlotte@localhost: Yes, their coffee is amazing.",
    "Matthew@localhost: I'll have to check it out.",
    "Olivia@localhost: What's your favorite TV show?",
    "Benjamin@localhost: I really enjoy watching 'Friends'.",
    "Amelia@localhost: It's a classic!",
    "James@localhost: I couldn't agree more.",
    "Emma@localhost: Have you been to the new art exhibition?",
    "William@localhost: No, not yet. Is it worth visiting?",
    "Sophia@localhost: Absolutely! The artwork is stunning.",
    "Daniel@localhost: I'll make sure to go.",
    "Emily@localhost: What's your favorite genre of music?",
    "Alexander@localhost: I listen to a bit of everything.",
    "Oliver@localhost: That's great. Music is so diverse.",
    "Ava@localhost: I couldn't agree more.",
];

export default GenerateRandomTerminalInputsConstants;
