const GenerateRandomTerminalInputsConstants: string[] = [
    "John: Hey, what's up?",
    "Emma: Not much, just chilling.",
    "Michael: Did you watch the latest episode of that show?",
    "Sophia: Yeah, it was amazing!",
    "David: I can't wait for the next season.",
    "Olivia: Just finished reading a great book.",
    "Daniel: What's the book about?",
    "Emily: It's a mystery novel with a twist.",
    "Matthew: Sounds interesting. I'll check it out.",
    "Ava: Let me know what you think!",
    "William: Have you tried the new restaurant in town?",
    "Sofia: No, not yet. Is it any good?",
    "James: Yes, the food is delicious!",
    "Charlotte: I'll have to give it a try.",
    "Benjamin: Did you hear about the concert next week?",
    "Amelia: Yeah, I already got my tickets.",
    "Henry: It's going to be an amazing show.",
    "Mia: I can't wait to see the band live.",
    "Elijah: Have you seen the latest movie?",
    "Harper: No, not yet. Is it worth watching?",
    "Alexander: Definitely! It's a must-see.",
    "Abigail: I'll make sure to watch it.",
    "Daniel: What are your plans for the weekend?",
    "Elizabeth: I'm going hiking with some friends.",
    "Joseph: That sounds like a lot of fun.",
    "Evelyn: Do you have any recommendations for a good book?",
    "William: I recently read a great sci-fi novel.",
    "Sophia: What's the title of the book?",
    "Oliver: It's called 'The Expanse'.",
    "Ava: I'll add it to my reading list.",
    "Michael: Did you watch the latest sports game?",
    "Isabella: Yeah, it was an intense match.",
    "Jacob: Who won in the end?",
    "Mia: The home team came out on top.",
    "Emily: I'm glad they won.",
    "Daniel: Have you tried the new coffee shop?",
    "Charlotte: Yes, their coffee is amazing.",
    "Matthew: I'll have to check it out.",
    "Olivia: What's your favorite TV show?",
    "Benjamin: I really enjoy watching 'Friends'.",
    "Amelia: It's a classic!",
    "James: I couldn't agree more.",
    "Emma: Have you been to the new art exhibition?",
    "William: No, not yet. Is it worth visiting?",
    "Sophia: Absolutely! The artwork is stunning.",
    "Daniel: I'll make sure to go.",
    "Emily: What's your favorite genre of music?",
    "Alexander: I listen to a bit of everything.",
    "Oliver: That's great. Music is so diverse.",
    "Ava: I couldn't agree more.",
];

export default GenerateRandomTerminalInputsConstants;
